Archival Object request bug
BCDigLib/request_list pull request #4
Opened 2022-12-07 16:22 UTC by akofa-a

check to see that the archival object has a top container reference before showing the 'add to request list' button

2022-12-07 18:05 UTC, jessemartinez requested changes
Here's some feedback on the PR code.

2022-12-07 18:05 UTC, jessemartinez commented on public/models/harvard_aeon/archival_object_mapper.rb
> +      Rails.logger.error(item['json']['jsonmodel_type'])
remove this debug line

2022-12-07 18:05 UTC, jessemartinez commented on public/models/harvard_aeon/archival_object_mapper.rb
> +            true
you should explicitly return true to break out of the loop and the method
```suggestion
           return  true
```

2022-12-07 18:05 UTC, jessemartinez commented on public/models/harvard_aeon/archival_object_mapper.rb
> +      end
it makes more sense to return false outside the top-most if block so it catches everything
```suggestion
      end 
      return false
```

2022-12-07 18:05 UTC, jessemartinez commented on public/models/harvard_aeon/archival_object_mapper.rb
> +            false
no need to return false inside the loop; if the first loop fails then we want to check each `my_instance` value to see if it matches

2022-12-07 19:06 UTC, akofa-a commented
@jessemartinez I've made the suggested changes! Thanks!

2022-12-07 21:45 UTC, jessemartinez requested changes
A few more corrections

2022-12-07 21:45 UTC, jessemartinez commented on public/models/harvard_aeon/archival_object_mapper.rb
>            if my_instance['instance_type'] and my_instance['instance_type'] == "text" and my_instance['subcontainer'] and my_instance['subcontainer']['topcontainer'] and my_instance['subcontainter']['
This is full of misspelled words. It should be `sub_container` and `top_container`

2022-12-07 21:45 UTC, jessemartinez commented on public/models/harvard_aeon/archival_object_mapper.rb
> +      return false;
Syntax error. No need for semicolon ;-)

2022-12-08 15:37 UTC, jessemartinez commented on public/models/harvard_aeon/archival_object_mapper.rb
> +      return false;
The semicolon still needs to be removed

2022-12-08 20:18 UTC, merged

2022-12-08 20:19 UTC, jessemartinez commented
looks good. just make sure it works on the server!